# Generated by Django 4.2.20 on 2025-06-23 05:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customerdata',
            name='unique_email_per_user',
        ),
        migrations.AddField(
            model_name='customerdata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerdata',
            name='meta_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='customerdata',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customerdata',
            name='contact_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customerdata',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='customerdata',
            name='email_id',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='customerdata',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customerdata',
            name='person_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name='uploadedfile',
            constraint=models.UniqueConstraint(condition=models.Q(('email_id__isnull', False)), fields=('user', 'email_id'), name='unique_email_per_user'),
        ),
    ]
