# Generated by Django 4.2.20 on 2025-07-04 07:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_remove_customerdata_unique_email_per_user_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='uploadedfile',
            name='unique_email_per_user',
        ),
        migrations.RemoveField(
            model_name='customerdata',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='customerdata',
            name='company_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='customerdata',
            name='contact_no',
            field=models.CharField(default='0000000000', max_length=20),
        ),
        migrations.AlterField(
            model_name='customerdata',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='customerdata',
            name='email_id',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='customerdata',
            name='location',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='customerdata',
            name='meta_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='customerdata',
            name='person_name',
            field=models.CharField(default='Anonymous', max_length=255),
        ),
        migrations.AddConstraint(
            model_name='customerdata',
            constraint=models.UniqueConstraint(condition=models.Q(('email_id__isnull', False)), fields=('user', 'email_id'), name='unique_email_per_user'),
        ),
    ]
