# Generated by Django 4.2.20 on 2025-07-08 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_importedfile_dynamicdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicdata',
            name='source_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamicdata', to='crm.importedfile'),
        ),
    ]
